version: '2'
services:
  fix-mariadb-volume-ownership:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - '${WEBAPP_STORAGE_HOME}/mariadb_data:/bitnami'
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '${WEBAPP_STORAGE_HOME}/mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - fix-mariadb-volume-ownership
  wordpress:
    image: 'bitnami/wordpress:latest'
    user: root
    ports:
      - '8000:80'
    volumes:
      - '${WEBAPP_STORAGE_HOME}/site/wwwroot:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes