version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/db:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    depends_on: db
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
        - ${WEBAPP_STORAGE_HOME}/LogFiles:/var/log